// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XYZHotels.Contexts;

#nullable disable

namespace XYZHotels.Migrations
{
    [DbContext(typeof(XYZHotelContext))]
    partial class XYZHotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XYZHotels.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Facility")
                        .HasColumnType("text");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HotelId");

                    b.ToTable("hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            Facility = "Lake-Side",
                            HotelName = "PQR"
                        },
                        new
                        {
                            HotelId = 2,
                            Facility = "Main-Road",
                            HotelName = "STU"
                        });
                });

            modelBuilder.Entity("XYZHotels.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<bool>("Balcony")
                        .HasColumnType("boolean");

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HotelId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("RoomId");

                    b.HasIndex("HotelId");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            RoomId = "1",
                            Balcony = true,
                            BedType = "Single",
                            HotelId = 1,
                            Price = 10000f
                        },
                        new
                        {
                            RoomId = "2",
                            Balcony = false,
                            BedType = "Double",
                            HotelId = 1,
                            Price = 8000.5f
                        });
                });

            modelBuilder.Entity("XYZHotels.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<byte[]>("Key")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("users");
                });

            modelBuilder.Entity("XYZHotels.Models.Room", b =>
                {
                    b.HasOne("XYZHotels.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });
#pragma warning restore 612, 618
        }
    }
}
